### ISSUE TITLE
Not an issue but a question

### ISSUE THREAD

**Issue by MHMLiveGaming** [IngPleb/qb-characterkill#3]
Is it possible to automate the character kill so Admins don't need to be online to manually kill?

**Comment by thezarpxs** [comment]
If the player is conected you can execute the comand from the tx live console I think

**Comment by IngPleb** [comment]
I am not really sure if qb-core made any changes to how are the commands registered but I guess you could use an event to and make some script to automate the process

**Comment by thezarpxs** [comment]
Why you want yo automate the process?

**Comment by MHMLiveGaming** [comment]
> 

Hi,its sorted. Its been auomated so that when a character reaches zero, the player can only press E and be CK'd. Basically, we moved parts of the CK code directly in to qb-ambulance job.
