### ISSUE TITLE
DELETE FROM database not fully working

### ISSUE THREAD

**Issue by Shi17** [IngPleb/qb-characterkill#4]
Sup, I have a problem with deleting these two values from database :
exports.oxmysql.execute('DELETE FROM player_contacts WHERE citizenid =?', { citizenid })
exports.oxmysql.execute('DELETE FROM playerskins WHERE citizenid =?', { citizenid })

Whenever i run ck command, first 4 get deleted from database, but those 2 wont.. could you give me some advice on how to repair this?
Also I wanted to add some new delete, everything was set right, still it did not deleted.. My last idea is , that it might have to do something with Database it self and values configurated in those tables? But it is just my hunch.. 
Thanks for your help.

**Comment by IngPleb** [comment]
Well, this is definitely weird behaviour. Are there any errors in the server console while running the character deletion?

**Comment by Shi17** [comment]
Nie, práveže nie je tam v konzole žiadny error. Iba keď som si dal print za
každým deletom, tak som zistil, že prvé 4 fungujú, tie hodí do konzole a
potom nič. Môžem zajtra poslať screenshot ako to vyzerá?

(pardon som si až teraz všimol, že si Čech. 😅Prípadne nemáš Discord? Ale
ak ti vyhovuje github/email tak pohode. )

Dňa ne 19. 2. 2023, 12:40 Matěj Vnouček ***@***.***>
napísal(a):

**Comment by IngPleb** [comment]
Klidě si mě přidej na discordu, tam to dořešíme — IngPleb#5121
